// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: compatibility_test.proto

package main

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SomeBytes     []byte                 `protobuf:"bytes,1,opt,name=some_bytes,json=someBytes,proto3" json:"some_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_compatibility_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_compatibility_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_compatibility_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetSomeBytes() []byte {
	if x != nil {
		return x.SomeBytes
	}
	return nil
}

type RequiredFieldTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequiredField string                 `protobuf:"bytes,13,opt,name=required_field,json=requiredField,proto3" json:"required_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiredFieldTest) Reset() {
	*x = RequiredFieldTest{}
	mi := &file_compatibility_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredFieldTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredFieldTest) ProtoMessage() {}

func (x *RequiredFieldTest) ProtoReflect() protoreflect.Message {
	mi := &file_compatibility_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredFieldTest.ProtoReflect.Descriptor instead.
func (*RequiredFieldTest) Descriptor() ([]byte, []int) {
	return file_compatibility_test_proto_rawDescGZIP(), []int{1}
}

func (x *RequiredFieldTest) GetRequiredField() string {
	if x != nil {
		return x.RequiredField
	}
	return ""
}

type WktTestMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration      *durationpb.Duration    `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	StructField   *structpb.Struct        `protobuf:"bytes,3,opt,name=struct_field,json=structField,proto3" json:"struct_field,omitempty"`
	ValueField    *structpb.Value         `protobuf:"bytes,4,opt,name=value_field,json=valueField,proto3" json:"value_field,omitempty"`
	ListValue     *structpb.ListValue     `protobuf:"bytes,5,opt,name=list_value,json=listValue,proto3" json:"list_value,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask  `protobuf:"bytes,6,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Any           *anypb.Any              `protobuf:"bytes,7,opt,name=any,proto3" json:"any,omitempty"`
	StringValue   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	Int32Value    *wrapperspb.Int32Value  `protobuf:"bytes,9,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int64Value    *wrapperspb.Int64Value  `protobuf:"bytes,10,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	BoolValue     *wrapperspb.BoolValue   `protobuf:"bytes,11,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	BytesValue    *wrapperspb.BytesValue  `protobuf:"bytes,12,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WktTestMessage) Reset() {
	*x = WktTestMessage{}
	mi := &file_compatibility_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WktTestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WktTestMessage) ProtoMessage() {}

func (x *WktTestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_compatibility_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WktTestMessage.ProtoReflect.Descriptor instead.
func (*WktTestMessage) Descriptor() ([]byte, []int) {
	return file_compatibility_test_proto_rawDescGZIP(), []int{2}
}

func (x *WktTestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WktTestMessage) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *WktTestMessage) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

func (x *WktTestMessage) GetValueField() *structpb.Value {
	if x != nil {
		return x.ValueField
	}
	return nil
}

func (x *WktTestMessage) GetListValue() *structpb.ListValue {
	if x != nil {
		return x.ListValue
	}
	return nil
}

func (x *WktTestMessage) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *WktTestMessage) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

func (x *WktTestMessage) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValue
	}
	return nil
}

func (x *WktTestMessage) GetInt32Value() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Value
	}
	return nil
}

func (x *WktTestMessage) GetInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Value
	}
	return nil
}

func (x *WktTestMessage) GetBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolValue
	}
	return nil
}

func (x *WktTestMessage) GetBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

var File_compatibility_test_proto protoreflect.FileDescriptor

const file_compatibility_test_proto_rawDesc = "" +
	"\n" +
	"\x18compatibility_test.proto\x12\x04main\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a google/protobuf/field_mask.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/api/field_behavior.proto\",\n" +
	"\vTestMessage\x12\x1d\n" +
	"\n" +
	"some_bytes\x18\x01 \x01(\fR\tsomeBytes\"?\n" +
	"\x11RequiredFieldTest\x12*\n" +
	"\x0erequired_field\x18\r \x01(\tB\x03\xe0A\x02R\rrequiredField\"\xca\x05\n" +
	"\x0eWktTestMessage\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12:\n" +
	"\fstruct_field\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vstructField\x127\n" +
	"\vvalue_field\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\n" +
	"valueField\x129\n" +
	"\n" +
	"list_value\x18\x05 \x01(\v2\x1a.google.protobuf.ListValueR\tlistValue\x129\n" +
	"\n" +
	"field_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12&\n" +
	"\x03any\x18\a \x01(\v2\x14.google.protobuf.AnyR\x03any\x12?\n" +
	"\fstring_value\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\vstringValue\x12<\n" +
	"\vint32_value\x18\t \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"int32Value\x12<\n" +
	"\vint64_value\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"int64Value\x129\n" +
	"\n" +
	"bool_value\x18\v \x01(\v2\x1a.google.protobuf.BoolValueR\tboolValue\x12<\n" +
	"\vbytes_value\x18\f \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"bytesValueB\x99\x01\n" +
	"\bcom.mainB\x16CompatibilityTestProtoP\x01ZEgithub.com/redpanda-data/protoc-gen-go-mcp/cmd/protoc-gen-go-mcp/main\xa2\x02\x03MXX\xaa\x02\x04Main\xca\x02\x04Main\xe2\x02\x10Main\\GPBMetadata\xea\x02\x04Mainb\x06proto3"

var (
	file_compatibility_test_proto_rawDescOnce sync.Once
	file_compatibility_test_proto_rawDescData []byte
)

func file_compatibility_test_proto_rawDescGZIP() []byte {
	file_compatibility_test_proto_rawDescOnce.Do(func() {
		file_compatibility_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compatibility_test_proto_rawDesc), len(file_compatibility_test_proto_rawDesc)))
	})
	return file_compatibility_test_proto_rawDescData
}

var file_compatibility_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_compatibility_test_proto_goTypes = []any{
	(*TestMessage)(nil),            // 0: main.TestMessage
	(*RequiredFieldTest)(nil),      // 1: main.RequiredFieldTest
	(*WktTestMessage)(nil),         // 2: main.WktTestMessage
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 4: google.protobuf.Duration
	(*structpb.Struct)(nil),        // 5: google.protobuf.Struct
	(*structpb.Value)(nil),         // 6: google.protobuf.Value
	(*structpb.ListValue)(nil),     // 7: google.protobuf.ListValue
	(*fieldmaskpb.FieldMask)(nil),  // 8: google.protobuf.FieldMask
	(*anypb.Any)(nil),              // 9: google.protobuf.Any
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),  // 11: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 12: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),   // 13: google.protobuf.BoolValue
	(*wrapperspb.BytesValue)(nil),  // 14: google.protobuf.BytesValue
}
var file_compatibility_test_proto_depIdxs = []int32{
	3,  // 0: main.WktTestMessage.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 1: main.WktTestMessage.duration:type_name -> google.protobuf.Duration
	5,  // 2: main.WktTestMessage.struct_field:type_name -> google.protobuf.Struct
	6,  // 3: main.WktTestMessage.value_field:type_name -> google.protobuf.Value
	7,  // 4: main.WktTestMessage.list_value:type_name -> google.protobuf.ListValue
	8,  // 5: main.WktTestMessage.field_mask:type_name -> google.protobuf.FieldMask
	9,  // 6: main.WktTestMessage.any:type_name -> google.protobuf.Any
	10, // 7: main.WktTestMessage.string_value:type_name -> google.protobuf.StringValue
	11, // 8: main.WktTestMessage.int32_value:type_name -> google.protobuf.Int32Value
	12, // 9: main.WktTestMessage.int64_value:type_name -> google.protobuf.Int64Value
	13, // 10: main.WktTestMessage.bool_value:type_name -> google.protobuf.BoolValue
	14, // 11: main.WktTestMessage.bytes_value:type_name -> google.protobuf.BytesValue
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_compatibility_test_proto_init() }
func file_compatibility_test_proto_init() {
	if File_compatibility_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compatibility_test_proto_rawDesc), len(file_compatibility_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_compatibility_test_proto_goTypes,
		DependencyIndexes: file_compatibility_test_proto_depIdxs,
		MessageInfos:      file_compatibility_test_proto_msgTypes,
	}.Build()
	File_compatibility_test_proto = out.File
	file_compatibility_test_proto_goTypes = nil
	file_compatibility_test_proto_depIdxs = nil
}
